baseURL = 'http://frx.crazyfrank.top/'
languageCode = 'en-us'
title = 'frx'

[module]
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"
    disable = false

# 启用 Git 信息
enableGitInfo = true

# 启用 emoji 支持
enableEmoji = true

# 代码高亮配置
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = true
    lineNumbersInTable = false
    tabWidth = 4

# 菜单配置
[menu]
  [[menu.main]]
    name = "Documentation"
    url = "/docs/"
    weight = 10
  [[menu.main]]
    name = "GitHub"
    url = "https://github.com/crazyfrankie/frx"
    weight = 50

[params]
  description = "Modern Go libraries for scalable applications"
  author = "crazyfrank"
  
  # 网站图标配置
  favicon = "/favicon.ico"
  logo = "/logo.svg"
  
  # Docsy 主题参数
  github_repo = "https://github.com/crazyfrankie/frx-doc"
  github_branch = "main"
  
  # 版本配置
  version_menu = "Versions"
  version = "v0.0.2"
  
  # UI 配置
  [params.ui]
    sidebar_menu_compact = true
    breadcrumb_disable = false
    sidebar_search_disable = false
    navbar_logo = true
    footer_about_enable = false
  
  # 链接配置
  [params.links]
    [[params.links.developer]]
      name = "GitHub"
      url = "https://github.com/crazyfrankie/frx"
      icon = "fab fa-github"
      desc = "Development takes place here!"

